### ISSUE TITLE
Para um cara daora

### ISSUE THREAD

**Issue by joevtap** [queirozz8/ABOUT-ME---SOBRE-MIM#1]
Oi Henrique, tudo bem?

Vi que você me seguiu. Acho engraçado que às vezes pessoas que não conheço me seguem do nada aqui, nem tenho tanta coisa pra mostrar. Quando eu vejo alguém como você na lista de seguidores, jovem, faminto, eu tenho vontade é de falar pessoalmente que ela tem um futuro brilhante. 

Então. Bom. Você tem um futuro brilhante. Uma chama queima dentro de você.

Continue assim meu bom, busque por novas alturas sempre. Conhecimento é um bem infindo. Continue a aprender todos os dias e alimente sua fome por novas experiências e aprendizados.

Tudo de bom.

Tem pessoas torcendo por você e você nem sabe.

**Comment by queirozz8** [comment]
Opa, prazer em te conhecer mano!
Eu realmente não esperava que você iria realmente se importar que eu te segui; na verdade, meu irmão te segue, fui olhar e achei seu GitHub bem inspirador, depois dá uma passada no GitHub dele caso queira dar uma olhada: https://github.com/devvluan.

Cara, eu agradeço muito pelas coisas que você disse, eu realmente me senti inspirado kkkkkkk. Eu acredito que eu estou indo de certa forma para um caminho bom. Desde os 13 eu faço essas coisas, mas aos 14 eu melhorei ainda mais: 

Eu estudo programação (Maior foco dentre todas as outras coisas), estudo sobre comunicação e persuasão (até porque muitos programadores não tem muitas soft skills, tê-las com certeza me daria uma vantagem em comparação aos outros). Tentando ser melhor à cada dia, tomara que tudo dê certo.

Reforçando, eu agradeço muito pelas palavras, eu me senti verdadeiramente inspirado. Pode confiar que eu vou continuar assim, se não, até melhor. Vou anotar as coisas que você disse.

Tudo de bom pra você também meu mano, muito prazer em te conhecer.
Obrigado por ler :)
